name: task_manager
description: A comprehensive task management app with local storage
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.1.1

  # Local Storage
  shared_preferences: ^2.2.2

  # Notifications
  flutter_local_notifications: ^16.3.0
  timezone: ^0.9.2

  # File Operations
  path_provider: ^2.1.1
  share_plus: ^7.2.1

  # Utilities
  uuid: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
